title: Banco Mercante
descripton: ""
url: "bancomercante.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

remote_theme: b2a3e8/jekyll-theme-console

style: light # dark (default) or light

# footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# google_analytics: UA-NNNNNNNN-N

plugins:
  - jekyll-seo-tag
