title: Banco Mercante
descripton: ""
url: "bancomercante.com"

header_pages:
  - index.md
  - services.md
  - about.md
  - contact.md

remote_theme: b2a3e8/jekyll-theme-console

style: light # dark (default) or light

footer: 'Class A Banking Licence No: RFSA-003-2024 | All rights reserved'

plugins:
  - jekyll-seo-tag

# google_analytics: UA-NNNNNNNN-N
